# Generated by Django 5.1.3 on 2024-11-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('interests', models.CharField(max_length=200)),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
